# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumbersRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('skype_id', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('forward_number', models.CharField(max_length=30)),
                ('how_many_per_day', models.CharField(max_length=30)),
                ('delivery_time', models.CharField(max_length=30)),
                ('quantity', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PvaAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('skype_id', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.CharField(max_length=30)),
            ],
        ),
    ]
